<?php

use Infocyph\Epicrypt\Crypto\Support\SodiumFunctions;
use Infocyph\Epicrypt\DataProtection\OpenSSL\OpenSslFunctions;
use Infocyph\Epicrypt\Integrity\Support\HashFunctions;
use Infocyph\Epicrypt\Password\Support\PasswordFunctions;

it('exposes the full required sodium/hash/openssl/password native function surface', function () {
    $coverage = [
        SodiumFunctions::class => [
            'sodium_bin2base64',
            'sodium_base642bin',
            'sodium_bin2hex',
            'sodium_hex2bin',
            'sodium_compare',
            'sodium_memcmp',
            'sodium_memzero',
            'sodium_randombytes_buf',
            'sodium_randombytes_uniform',
            'sodium_crypto_aead_xchacha20poly1305_ietf_encrypt',
            'sodium_crypto_aead_xchacha20poly1305_ietf_decrypt',
            'sodium_crypto_aead_chacha20poly1305_ietf_encrypt',
            'sodium_crypto_aead_chacha20poly1305_ietf_decrypt',
            'sodium_crypto_aead_aes256gcm_encrypt',
            'sodium_crypto_aead_aes256gcm_decrypt',
            'sodium_crypto_secretbox',
            'sodium_crypto_secretbox_open',
            'sodium_crypto_box',
            'sodium_crypto_box_open',
            'sodium_crypto_box_keypair',
            'sodium_crypto_box_seed_keypair',
            'sodium_crypto_box_publickey',
            'sodium_crypto_box_secretkey',
            'sodium_crypto_box_keypair_from_secretkey_and_publickey',
            'sodium_crypto_box_seal',
            'sodium_crypto_box_seal_open',
            'sodium_crypto_sign',
            'sodium_crypto_sign_open',
            'sodium_crypto_sign_detached',
            'sodium_crypto_sign_verify_detached',
            'sodium_crypto_sign_keypair',
            'sodium_crypto_sign_seed_keypair',
            'sodium_crypto_sign_publickey',
            'sodium_crypto_sign_secretkey',
            'sodium_crypto_sign_keypair_from_secretkey_and_publickey',
            'sodium_crypto_auth',
            'sodium_crypto_auth_verify',
            'sodium_crypto_onetimeauth',
            'sodium_crypto_onetimeauth_verify',
            'sodium_crypto_generichash',
            'sodium_crypto_generichash_init',
            'sodium_crypto_generichash_update',
            'sodium_crypto_generichash_final',
            'sodium_crypto_pwhash',
            'sodium_crypto_pwhash_str',
            'sodium_crypto_pwhash_str_verify',
            'sodium_crypto_pwhash_str_needs_rehash',
            'sodium_crypto_pwhash_scryptsalsa208sha256',
            'sodium_crypto_pwhash_scryptsalsa208sha256_str',
            'sodium_crypto_pwhash_scryptsalsa208sha256_str_verify',
            'sodium_crypto_kdf_derive_from_key',
            'sodium_crypto_kx_keypair',
            'sodium_crypto_kx_seed_keypair',
            'sodium_crypto_kx_client_session_keys',
            'sodium_crypto_kx_server_session_keys',
            'sodium_crypto_scalarmult',
            'sodium_crypto_scalarmult_base',
            'sodium_crypto_core_ristretto255_add',
            'sodium_crypto_core_ristretto255_sub',
            'sodium_crypto_core_ristretto255_scalar_add',
            'sodium_crypto_core_ristretto255_scalar_sub',
            'sodium_crypto_core_ristretto255_scalar_mul',
            'sodium_crypto_scalarmult_ristretto255',
            'sodium_crypto_scalarmult_ristretto255_base',
            'sodium_crypto_secretstream_xchacha20poly1305_init_push',
            'sodium_crypto_secretstream_xchacha20poly1305_push',
            'sodium_crypto_secretstream_xchacha20poly1305_init_pull',
            'sodium_crypto_secretstream_xchacha20poly1305_pull',
            'sodium_crypto_secretstream_xchacha20poly1305_rekey',
        ],
        HashFunctions::class => [
            'hash',
            'hash_algos',
            'hash_file',
            'hash_init',
            'hash_update',
            'hash_update_file',
            'hash_update_stream',
            'hash_final',
            'hash_copy',
            'hash_hmac',
            'hash_hmac_algos',
            'hash_hmac_file',
            'hash_pbkdf2',
            'hash_hkdf',
        ],
        OpenSslFunctions::class => [
            'openssl_encrypt',
            'openssl_decrypt',
            'openssl_cipher_iv_length',
            'openssl_cipher_key_length',
            'openssl_get_cipher_methods',
            'openssl_sign',
            'openssl_verify',
            'openssl_pkey_new',
            'openssl_pkey_get_private',
            'openssl_pkey_get_public',
            'openssl_pkey_export',
            'openssl_pkey_export_to_file',
            'openssl_pkey_get_details',
            'openssl_public_encrypt',
            'openssl_private_decrypt',
            'openssl_private_encrypt',
            'openssl_public_decrypt',
            'openssl_seal',
            'openssl_open',
            'openssl_pbkdf2',
            'openssl_dh_compute_key',
            'openssl_x509_read',
            'openssl_x509_parse',
            'openssl_x509_checkpurpose',
            'openssl_x509_verify',
            'openssl_x509_export',
            'openssl_x509_export_to_file',
            'openssl_x509_fingerprint',
            'openssl_csr_new',
            'openssl_csr_sign',
            'openssl_csr_export',
            'openssl_csr_export_to_file',
            'openssl_csr_get_public_key',
            'openssl_csr_get_subject',
            'openssl_pkcs7_encrypt',
            'openssl_pkcs7_decrypt',
            'openssl_pkcs7_sign',
            'openssl_pkcs7_verify',
            'openssl_cms_encrypt',
            'openssl_cms_decrypt',
            'openssl_cms_sign',
            'openssl_cms_verify',
            'openssl_random_pseudo_bytes',
        ],
        PasswordFunctions::class => [
            'password_hash',
            'password_verify',
            'password_needs_rehash',
            'password_get_info',
            'password_algos',
        ],
    ];

    foreach ($coverage as $class => $methods) {
        foreach ($methods as $method) {
            expect(method_exists($class, $method))->toBeTrue();
        }
    }
});
